### ISSUE TITLE
Always just prints "Hello, world!" on my box

### ISSUE THREAD

**Issue by BartMassey** [Lutetium-Vanadium/cargo-playground#1]
Running `cargo playground` with no arguments or with a crate-name argument merely prints `"Hello, world!"`. Would be better to fail with a help message on unknown commands and when "--help" is supplied.

**Comment by BartMassey** [comment]
Actually, I can't get `cargo playground` to print anything but `"Hello, world!"` on my box no matter what I do. Debian Buster, `tmux` installed, `cargo-playground` installed by `cargo install cargo-playground`.

**Comment by BartMassey** [comment]
Looks like current git works fine. Apparently just an old version on `crates.io`?

**Comment by Lutetium-Vanadium** [comment]
Unfortunately cargo-playground was already registered by someone, but never used. I've tried contacting whoever registered it, but I've had no luck so far.

**Comment by Lutetium-Vanadium** [comment]
I've added a disclaimer in the README, but hopefully they will reply to my email soon.
