### ISSUE TITLE
Playground commands in bash history

### ISSUE THREAD

**Issue by BartMassey** [Lutetium-Vanadium/cargo-playground#2]
`cd /tmp/cargo-playground/playground-1616203988 && /home/bart/.cargo/bin/cargo-playground watch playground-1616203988`

Not ideal: probably need to invoke the shell with different arguments.

**Comment by Lutetium-Vanadium** [comment]
Hmm, I use fish shell, and since it opened a new pane, it didn't add to the history. I definitely should have tested on other shells. Will fix this with the next commit.

**Comment by Lutetium-Vanadium** [comment]
Can you please update to the latest version and check if it adds it to the bash history?

**Comment by BartMassey** [comment]
It does.

```
cargo playground new -n bogosity2
 cd /tmp/cargo-playground/bogosity2 && /home/bart/.cargo/bin/cargo-playground watch bogosity2
```

**Comment by Lutetium-Vanadium** [comment]
Can you please try it with the version in the pr #5?

I'm sorry to have to ask you every time, but for some reason it works fine on my computer.

**Comment by BartMassey** [comment]
That seems to have got it.

**Comment by Lutetium-Vanadium** [comment]
Cool!
