### ISSUE TITLE
Playgrounds are kept in /tmp

### ISSUE THREAD

**Issue by BartMassey** [Lutetium-Vanadium/cargo-playground#3]
Keeping playgrounds in `/tmp` is a bit dangerous, as they may be removed at any time — especially after a reboot. Should probably be kept someplace more permanent, perhaps `$HOME/.cache/cargo-playground` or `$HOME/.cargo-playground`

**Comment by Lutetium-Vanadium** [comment]
My initial plan was to have this clear by themselves (whenever the host OS decides to), as these are meant to be temporary playgrounds. However, I'm open to the idea of having settings to determine where the playgrounds are stored.

**Comment by BartMassey** [comment]
I guess I feel like if they are meant to be temporary having a way to list and reopen them seems a little misleading. Your call, though!

**Comment by Lutetium-Vanadium** [comment]
Hmm yeah.

I think the way I want this to be resolved is to use an environment variable (like `CARGO_PLAYGROUND_DIR`) to set where it goes, and falling back on the temp directory. I'll also add a `clean` command so if `CARGO_PLAYGROUND_DIR` is set to some other directory, there is still an easy way to delete playgrounds so it doesn't take too much space.
